NumPY


In [1]:

import numpy as np


In [2]:
np.__version__

'1.24.3'

In [12]:
a=[1,2,3,4,5]
np_a=np.array(a)
print(np_a)
type(np_a)
np_a.ndim

[1 2 3 4 5]


1

In [4]:
#example-2
b=[10,20,30,40]
np1=np.array(b)
print(np1)

[10 20 30 40]


In [5]:
np1

array([10, 20, 30, 40])

Creating NumPy Arrays

In [7]:
a=np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [8]:
a=np.array((1,2,3,4))
a

array([1, 2, 3, 4])

In [9]:
type(a)

numpy.ndarray

In [10]:
a.ndim

1

In [13]:
a=np.array(45)
print(a)
type(a)
a.ndim

45


0

Functions for creating Arrays

In [15]:
a=np.arange(10,200,10)
print(a)

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190]


In [17]:
b=np.arange(20,500,50)
b

array([ 20,  70, 120, 170, 220, 270, 320, 370, 420, 470])

In [18]:
print(b)

[ 20  70 120 170 220 270 320 370 420 470]


In [19]:
c=np.arange(50,1000,50)
print(c)

[ 50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900
 950]


In [21]:
#linspace
c=np.linspace(0,100,11)
print(c)


[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [22]:
d=np.linspace(10,200,40)
print(d)
type(d)

[ 10.          14.87179487  19.74358974  24.61538462  29.48717949
  34.35897436  39.23076923  44.1025641   48.97435897  53.84615385
  58.71794872  63.58974359  68.46153846  73.33333333  78.20512821
  83.07692308  87.94871795  92.82051282  97.69230769 102.56410256
 107.43589744 112.30769231 117.17948718 122.05128205 126.92307692
 131.79487179 136.66666667 141.53846154 146.41025641 151.28205128
 156.15384615 161.02564103 165.8974359  170.76923077 175.64102564
 180.51282051 185.38461538 190.25641026 195.12820513 200.        ]


numpy.ndarray

In [23]:
e=np.zeros(3)
print(e)

[0. 0. 0.]


In [24]:
f=np.zeros(4)
print(f)

[0. 0. 0. 0.]


In [25]:
g=np.zeros(10)
print(g)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [26]:
#ones
a=np.ones(2)
print(a)

[1. 1.]


In [27]:
b=np.ones(3)
print(b)

[1. 1. 1.]


In [28]:
c=np.ones(5)

In [29]:
print(c)

[1. 1. 1. 1. 1.]


In [31]:
#random.randint
a=np.random.randint(0,50,2)
print(a)

[4 0]


In [32]:
a

array([4, 0])

In [33]:
np.random.randint(1,41,5)

array([37, 29, 29,  7, 34])